# Generated by Django 3.1.3 on 2021-11-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('effective_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
