# Generated by Django 3.1.3 on 2021-11-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locker',
            old_name='number',
            new_name='locker',
        ),
    ]
