# Generated by Django 3.1.3 on 2021-11-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0002_auto_20211111_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locker',
            old_name='locker',
            new_name='subject',
        ),
    ]
