# Generated by Django 3.1.3 on 2021-11-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0003_auto_20211111_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='content',
        ),
        migrations.AddField(
            model_name='locker',
            name='club',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='locker',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='locker',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='locker',
            name='effective_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='locker',
            name='expiration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='locker',
            name='size',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='locker',
            name='subject',
            field=models.CharField(max_length=4),
        ),
    ]
