# Generated by Django 3.1.3 on 2021-11-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0004_auto_20211111_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='club',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='locker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
