# Generated by Django 3.1.3 on 2021-11-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0005_auto_20211111_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locker',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locker',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
