# Generated by Django 3.1.3 on 2021-12-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0006_auto_20211111_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='create_date',
        ),
        migrations.AddField(
            model_name='locker',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
